version: "3.9"
 
services:
  dev:
    build: .  # Builds from the Dockerfile in the current directory
    container_name: dev-env
    hostname: dev-nas
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"  # Necessary for Synology NAS to avoid proxy issues
    volumes:
      - /volume1/docker/dev-env:/root  # Persistent home directory
      - /volume1/docker/dev-env/.ssh:/root/.ssh  # Persist SSH keys
    environment:
      - TERM=xterm-256color  # Better terminal support for Blink Shell
      - TZ=UTC  # Set your preferred timezone
    ports:
      - "60000-60010:60000-60010/udp"  # Mosh UDP port range
